spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
    platform: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
server:
  port: 8082